name: all CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-ci:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Format code
        run: yarn prettier --write --ignore-path .gitignore './**/*.{js,jsx,ts,tsx,json,css,scss}'
      - name: Lint code
        run: yarn lint

  backend-ci:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: ./backend/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Format code
        run: yarn format
      - name: Lint code
        run: yarn lint